### ISSUE TITLE
友链链接展示输出问题

### ISSUE THREAD

**Issue by hifocus** [dongyuanxin/theme-ad#13]
## 问题描述
友情链接页面在面对较为复杂的链接时 （例如 `https://blog.lim-light.com`）无法完整输出整个链接。

## 问题截图
![image](https://user-images.githubusercontent.com/30528433/54784978-013c4380-4c1d-11e9-9299-7f84bd96aee0.png)

![image](https://user-images.githubusercontent.com/30528433/54785006-0c8f6f00-4c1d-11e9-9042-3e4487cb2778.png)

## 主题配置相关代码
```yaml
  -
    nickname: 黎明余光
    avatar: /custom/lim-light.jpg
    site: https://blog.lim-light.com
    meta: "@idawnlight"
    show: true
```

可以参考 https://godbmw.com/friends/ 里面叫 “前端博客” 的友链。他的域名是 `https://refined-x.com` 但是输出只有 `x.com`。

## 已知问题
友链链接页面无法输出域名内的子域名，如 `blog.xxx.com`，但是可以输出 `www`。
友链链接页面无法输出域名内横杠 `-` 后的部分。

## 主题版本
Commit: https://github.com/dongyuanxin/theme-ad/commit/e596b340aa5bf526a59684b7bcccc855d3d283be
版本：v.2.3.0

## nodejs 版本
```sh
C:\Users\imhx\Documents\GitHub\Justhx.com>npm -v
6.1.0
```
## Hexo 版本
```sh
C:\Users\imhx>hexo cli -v
hexo-cli: 1.1.0
os: Windows_NT 10.0.17763 win32 x64
http_parser: 2.8.0
node: 10.7.0
v8: 6.7.288.49-node.15
uv: 1.22.0
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.32.0
napi: 3
openssl: 1.1.0h
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
